bss: __template refactor and reorder
Signed-off-by: Osamu Aoki <osamu@debian.org>

diff --git a/usr/bin/bss b/usr/bin/bss
--- a/usr/bin/bss
+++ b/usr/bin/bss
@@ -188,7 +188,7 @@ recoverable since the snapshot operation isn't recursive.
 
 Although this "$BSS" focuses on btrfs, there is minimal support for ext2/ext3
 (this includes ext4) for "$BSS copy ...", "$BSS backup ...", and "$BSS
-template". 
+template".
 
 Copyright 2022 Osamu Aoki <osamu@debian.org>, GPL 2+
 END_OF_HELP
@@ -992,40 +992,9 @@ __rsync_backup () {
   done
 }
 ##############################################################################
-__template () {
-  # make sure $BSS_DIR_BASE exists
-  if [ ! -d "$BSS_DIR_BASE" ]; then
-    if [ -z "$NOOP" ]; then
-      $SUDO mkdir -p "$BSS_DIR_BASE" >/dev/null
-      # match owner with the parent directory
-      $NOOP $SUDO chown "$FS_BASE_UID":"$FS_BASE_GID" "$BSS_DIR_BASE"
-    else
-      __echo 0 "'$BSS template' must not be used with --noop nor -n option."
-      exit $EXIT_ERROR
-    fi
-  fi
-  ############################################################################
-  #
-  # conf and filter template
-  #
-  ############################################################################
-  #
-  if [ "$FS_TYPE" = "btrfs" ]; then
-    ### CONFIGURATION ###
-    #
-    if [ -e "$BSS_CONF_BASE" ]; then
-      __echo 1 "Configuration file already exists: $BSS_CONF for BASE=$FS_BASE, keep it as is."
-      __echo 2 "Loading existing $BSS_CONF for BASE=$FS_BASE."
-      __load_config
-    else
-      if [ "$FS_BASE" = "/" ]; then
-        BSS_TMID_ACTION="filter"
-        __echo 2 "Suggest BSS_TMID_ACTION=\"filter\" in template since BASE=$FS_BASE (full system)"
-      else
-        BSS_TMID_ACTION="no_filter"
-      fi
-      __echo 2 "Make configuration $BSS_CONF_BASE for BASE=$FS_BASE UID=$FS_BASE_UID GID=$FS_BASE_GID"
-      $SUDO tee "$BSS_CONF_BASE" >/dev/null << END_OF_TEMPLATE
+__template_filter_btrfs () {
+  __echo 2 "Make configuration $BSS_CONF_BASE for BASE=$FS_BASE UID=$FS_BASE_UID GID=$FS_BASE_GID"
+  $SUDO tee "$BSS_CONF_BASE" >/dev/null << END_OF_TEMPLATE
 # $BSS configuration (btrfs)
 
 # This configuration file as generated by the "template" command.
@@ -1120,20 +1089,45 @@ BSS_SNAP_DEST=""
 # Many internal variables are prefixed with 'BSS_' to be unique to "$BSS" but
 # the dialog messages may just use the rest of variable name to be concise.
 END_OF_TEMPLATE
-      __echo 3 "Set owner to $FS_BASE_UID:$FS_BASE_GID for $BSS_CONF_BASE and $BSS_FLTR_BASE"
-    # shellcheck disable=SC2086
-      $NOOP $SUDO chown $FS_BASE_UID:$FS_BASE_GID "$BSS_CONF_BASE"
-    fi
-    #
-    ### FILTER ###
-    #
-    if [ -e "$BSS_FLTR_BASE" ] ; then
-      __echo 1 "Filter file already exists: $BSS_FLTR for BASE=$FS_BASE, keep it as is."
-    else
-      __echo 2 "Creating template: $BSS_FLTR for BASE=$FS_BASE."
-      if [ "$FS_BASE" = "/" ]; then
-        __echo 2 "Make filter $BSS_FLTR_BASE for BASE=$FS_BASE UID=$FS_BASE_UID GID=$FS_BASE_GID"
-      $SUDO tee "$BSS_FLTR_BASE" >/dev/null << END_OF_TEMPLATE
+}
+##############################################################################
+__template_conf_non_btrfs () {
+  __echo 2 "Make configuration $BSS_CONF_BASE for BASE=$FS_BASE UID=$FS_BASE_UID GID=$FS_BASE_GID"
+  $SUDO tee "$BSS_CONF_BASE" >/dev/null << END_OF_TEMPLATE
+# $BSS configuration (non-btrfs)
+
+# This configuration file as generated by the "template" command.
+#
+# BASE=$FS_BASE UID=$FS_BASE_UID GID=$FS_BASE_GID
+# FS=$FS_TYPE
+#
+
+### EXTRA PARAMETERS ###
+
+# convenience for "$BSS copy".  Set this to non-zero string to activate default destination.
+BSS_COPY_DEST=""
+# convenience for "$BSS copy".  Use this when destination is "1" ("1" works as alias).
+BSS_COPY_DEST1=""
+# convenience for "$BSS copy".  Use this when destination is "2" ("2" works as alias).
+BSS_COPY_DEST2=""
+# convenience for "$BSS copy".  Use this when destination is "3" ("3" works as alias).
+BSS_COPY_DEST3=""
+
+### NOTE ###
+
+# You can add a custom script to filter contents at TMID as $BSS_FLTR in this directory
+# You can add a custom script to run before copy as $PRE_COPY_SCRIPT in this directory
+# You can add a custom script to run after copy as $POST_COPY_SCRIPT in this directory
+# If BSS_COPY_DEST aliases 1,2,3 are used, script name to use should be suffixed accordingly.
+
+# Many internal variables are prefixed with 'BSS_' to be unique to "$BSS" but
+# the dialog messages may just use the rest of variable name to be concise.
+END_OF_TEMPLATE
+}
+##############################################################################
+__template_filter_root () {
+  __echo 2 "Make filter $BSS_FLTR_BASE for BASE=$FS_BASE UID=$FS_BASE_UID GID=$FS_BASE_GID"
+  $SUDO tee "$BSS_FLTR_BASE" >/dev/null << END_OF_TEMPLATE
 # $BSS filter (better to use relative path)
 #
 # BASE=$FS_BASE UID=$FS_BASE_UID GID=$FS_BASE_GID
@@ -1162,9 +1156,11 @@ find boot -type f -name 'initrd*' -exec rm -rf '{}' \;
 find boot -type f -name 'vmlinu*' -exec rm -rf '{}' \;
 
 END_OF_TEMPLATE
-    else
-      __echo 2 "Make filter $BSS_FLTR_BASE for BASE=$FS_BASE UID=$FS_BASE_UID GID=$FS_BASE_GID"
-      $SUDO tee "$BSS_FLTR_BASE" >/dev/null << END_OF_TEMPLATE
+}
+##############################################################################
+__template_filter_non_root () {
+  __echo 2 "Make filter $BSS_FLTR_BASE for BASE=$FS_BASE UID=$FS_BASE_UID GID=$FS_BASE_GID"
+  $SUDO tee "$BSS_FLTR_BASE" >/dev/null << END_OF_TEMPLATE
 # $BSS filter (better to use relative path)
 #
 # BASE=$FS_BASE UID=$FS_BASE_UID GID=$FS_BASE_GID
@@ -1196,6 +1192,57 @@ END_OF_TEMPLATE
 #find . -depth -type d -name '.git' -exec rm -rf '{}' \;
 
 END_OF_TEMPLATE
+}
+
+##############################################################################
+__template () {
+  # make sure $BSS_DIR_BASE exists
+  if [ ! -d "$BSS_DIR_BASE" ]; then
+    if [ -z "$NOOP" ]; then
+      $SUDO mkdir -p "$BSS_DIR_BASE" >/dev/null
+      # match owner with the parent directory
+      $NOOP $SUDO chown "$FS_BASE_UID":"$FS_BASE_GID" "$BSS_DIR_BASE"
+    else
+      __echo 0 "'$BSS template' must not be used with --noop nor -n option."
+      exit $EXIT_ERROR
+    fi
+  fi
+  ############################################################################
+  #
+  # conf and filter template
+  #
+  ############################################################################
+  #
+  if [ "$FS_TYPE" = "btrfs" ]; then
+    ### CONFIGURATION ###
+    #
+    if [ -e "$BSS_CONF_BASE" ]; then
+      __echo 1 "Configuration file already exists: $BSS_CONF for BASE=$FS_BASE, keep it as is."
+      __echo 2 "Loading existing $BSS_CONF for BASE=$FS_BASE."
+      __load_config
+    else
+      if [ "$FS_BASE" = "/" ]; then
+        BSS_TMID_ACTION="filter"
+        __echo 2 "Suggest BSS_TMID_ACTION=\"filter\" in template since BASE=$FS_BASE (full system)"
+      else
+        BSS_TMID_ACTION="no_filter"
+      fi
+      __template_conf_btrfs
+      __echo 3 "Set owner to $FS_BASE_UID:$FS_BASE_GID for $BSS_CONF_BASE and $BSS_FLTR_BASE"
+    # shellcheck disable=SC2086
+      $NOOP $SUDO chown $FS_BASE_UID:$FS_BASE_GID "$BSS_CONF_BASE"
+    fi
+    #
+    ### FILTER ###
+    #
+    if [ -e "$BSS_FLTR_BASE" ] ; then
+      __echo 1 "Filter file already exists: $BSS_FLTR for BASE=$FS_BASE, keep it as is."
+    else
+      __echo 2 "Creating template: $BSS_FLTR for BASE=$FS_BASE."
+      if [ "$FS_BASE" = "/" ]; then
+        __template_filter_root
+      else
+        __template_filter_non_root
       fi
       __echo 3 "Set owner to $FS_BASE_UID:$FS_BASE_GID for $BSS_CONF_BASE and $BSS_FLTR_BASE"
     # shellcheck disable=SC2086
@@ -1211,37 +1258,7 @@ END_OF_TEMPLATE
       __echo 1 "Configuration file already exists: $BSS_CONF for BASE=$FS_BASE, keep it as is."
       __echo 2 "Loading existing $BSS_CONF for BASE=$FS_BASE."
     else
-      __echo 2 "Make configuration $BSS_CONF_BASE for BASE=$FS_BASE UID=$FS_BASE_UID GID=$FS_BASE_GID"
-      $SUDO tee "$BSS_CONF_BASE" >/dev/null << END_OF_TEMPLATE
-# $BSS configuration (non-btrfs)
-
-# This configuration file as generated by the "template" command.
-#
-# BASE=$FS_BASE UID=$FS_BASE_UID GID=$FS_BASE_GID
-# FS=$FS_TYPE
-#
-
-### EXTRA PARAMETERS ###
-
-# convenience for "$BSS copy".  Set this to non-zero string to activate default destination.
-BSS_COPY_DEST=""
-# convenience for "$BSS copy".  Use this when destination is "1" ("1" works as alias).
-BSS_COPY_DEST1=""
-# convenience for "$BSS copy".  Use this when destination is "2" ("2" works as alias).
-BSS_COPY_DEST2=""
-# convenience for "$BSS copy".  Use this when destination is "3" ("3" works as alias).
-BSS_COPY_DEST3=""
-
-### NOTE ###
-
-# You can add a custom script to filter contents at TMID as $BSS_FLTR in this directory
-# You can add a custom script to run before copy as $PRE_COPY_SCRIPT in this directory
-# You can add a custom script to run after copy as $POST_COPY_SCRIPT in this directory
-# If BSS_COPY_DEST aliases 1,2,3 are used, script name to use should be suffixed accordingly.
-
-# Many internal variables are prefixed with 'BSS_' to be unique to "$BSS" but
-# the dialog messages may just use the rest of variable name to be concise.
-END_OF_TEMPLATE
+      __template_conf_non_btrfs
       __echo 3 "Set owner to $FS_BASE_UID:$FS_BASE_GID for $BSS_CONF_BASE and $BSS_FLTR_BASE"
       # shellcheck disable=SC2086
       $NOOP $SUDO chown $FS_BASE_UID:$FS_BASE_GID "$BSS_CONF_BASE"
